### ISSUE TITLE
On logout

### ISSUE THREAD

**Issue by Gehlhausen73** [cokert/Firelist#7]
When you logout it should take you to the home screen. Instead it left me looking at the list I had when logged in.

**Comment by cokert** [comment]
Make a pull request

**Comment by Gehlhausen73** [comment]
I will in the morning.  What do you develop with?

**Comment by cokert** [comment]
I develop using Atom on Mac, but you can use anything, really (VS Code, Sublime Text).  I need to update the readme/maybe add some documentation.
